[secrets."garage/rpc_secret"]
type = 'command'
command = 'openssl rand -hex 32'
# can't auto-rotate, because we still have some nodes outside of Nomad

[secrets."garage/admin_token"]
type = 'command'
command = 'openssl rand -hex 32'
rotate = true

[secrets."garage/metrics_token"]
type = 'command'
command = 'openssl rand -hex 32'
rotate = true
