[service_users."replicator"]
password_secret = "postgres/keeper/pg_repl_pwd"
username_secret = "postgres/keeper/pg_repl_username"


[secrets."postgres/keeper/pg_su_pwd"]
type = 'command'
command = 'openssl rand -base64 15'
description = 'postgres superuser password'

