# https://git.sr.ht/~bwolf/dotfiles/tree/master/item/.sops.yaml
keys:
  - &host-g3-3 age186sqmma0vsyh6tutgcak68mglxkmkxgc2sfz6dra0qmkhh8zfppqjy3u09
  - &host-g3-4 age13sdmfcrdh8dn05v594nr7dxywklmmanugj7j66ndaawy6hg6hs8sw5hcuz

creation_rules:
  - path_regex: secrets/.*3\.yaml$
    key_groups:
    - age:
      - *host-g3-3
  - path_regex: secrets/.*4\.yaml$
    key_groups:
    - age:
      - *host-g3-4




