keys:
   - &admin_hernad age13adxvst7kert59pad6uate0u9rdur7mchq8d7x57n2k334gccqaqetr6e3

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *admin_hernad
      #age:
      #- *admin_bob