keys:
   - &admin_hernad 453454CDE1C7FE12A2995CAC85669FDDE2456A79

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *admin_hernad
      #age:
      #- *admin_bob