#!/usr/bin/env bash
shopt -s nullglob;
for d in /sys/kernel/iommu_groups/*/devices/*;
do
    n="${d#*/iommu_groups/*}";
    n="${n%%/*}";
    printf 'IOMMU Group %s \t' "$n";
    lspci -nns "${d##*/}";
done | sort -h -k 3
