# General configuration 

[secrets."directory/guichet/web_hostname"]
type = 'user'
description = 'Public hostname from which Guichet is accessible via HTTP (e.g. guichet.example.com)'


# Mailing configuration

[secrets."directory/guichet/smtp_user"]
type = 'user'
description = 'SMTP username'

[secrets."directory/guichet/smtp_pass"]
type = 'user'
description = 'SMTP password'

[secrets."directory/guichet/smtp_server"]
type = 'user'
description = 'SMTP server address (hostname:port)'

[secrets."directory/guichet/mail_from"]
type = 'user'
description = 'E-mail address from which to send welcome emails to new users'

[secrets."directory/guichet/mail_domain"]
type = 'user'
description = 'E-mail domain for new users (e.g. example.com)'


# S3 configuration

[secrets."directory/guichet/s3_endpoint"]
type = 'user'
description = 'S3 endpoint URL'

[secrets."directory/guichet/s3_bucket"]
type = 'user'
description = 'S3 bucket in which to store data files (such as profile pictures)'

[secrets."directory/guichet/s3_region"]
type = 'user'
description = 'S3 region'

[secrets."directory/guichet/s3_access_key"]
type = 'user'
description = 'Garage access key for Guichet profile pictures'

[secrets."directory/guichet/s3_secret_key"]
type = 'user'
description = 'Garage secret key for Guichet profile pictures'
