# Jitsi secrets

[secrets."jitsi/jvb_pass"]
type = 'command'
rotate = true
command = 'openssl rand -base64 24'

[secrets."jitsi/jicofo_pass"]
type = 'command'
rotate = true
command = 'openssl rand -base64 24'


# SSL: Jitsi

[secrets."jitsi/jitsi.crt"]
type = 'SSL_CERT'
name = 'jitsi'
cert_domains = "['jitsi']"

[secrets."jitsi/jitsi.key"]
type = 'SSL_KEY'
name = 'jitsi'


# SSL: Jitsi auth

[secrets."jitsi/auth.jitsi.crt"]
type = 'SSL_CERT'
name = 'jitsi_auth'
cert_domains = "['auth.jitsi']"

[secrets."jitsi/auth.jitsi.key"]
type = 'SSL_KEY'
name = 'jitsi_auth'

